version: '3.4'

services:
  songsmicroservice:
    image: songsmicroservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://dsuntasig2001:87NA4IonBBQoRfXG@cluster0.em0dt.mongodb.net/songsDB?retryWrites=true&w=majority
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge